### ISSUE TITLE
What makes DigiByte stronger than others?

### ISSUE THREAD

**Issue by DGBNOOB** [DigiByte-Core/DGBio#78]
![Change to Since 2014, ](https://github.com/DigiByte-Core/DGBio/assets/136190014/5aedfd47-bcad-4575-a1dc-5e59d0028a1f)

Instead of "After 9 years of forward thinking development" change to "Since 2014," to avoid having to update every year.

**Comment by DennisPitallano** [comment]
We can create a simple JavaScript function that calculates the year difference from 2014 to the current year and appends this value to the paragraph. This way, we won't need to manually translate "Since 2014" into all available languages. Instead, only the computed value will need updating. This will automatically adjust every year.

For example:

2023: "After 9 years of forward-thinking development"
2024: "After 10 years of forward-thinking development"
2025: "After 11 years of forward-thinking development"
The same applies to other languages:

2023: "Nou na 9 jaar se toekomsgerigte ontwikkeling"
2024: "Nou na 10 jaar se toekomsgerigte ontwikkeling"
2025: "Nou na 11 jaar se toekomsgerigte ontwikkeling"


We can also adjust the footer section "About DigiByte" with the same paragraph to include this automatic year difference computation.

![image](https://github.com/DigiByte-Core/DGBio/assets/3394208/063e407c-ea7c-463a-89e0-ff922568a4cb)

**Comment by DGBNOOB** [comment]
Thank you @DennisPitallano 

I am going to go through again to identify issues that need to be addressed. I raised most of these issue, let me know if you have any questions on some of the recommendations I've made. 

Thank you.

**Comment by DGBNOOB** [comment]
@DennisPitallano this is excellent
